from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).parent.parent.parent

# Identity for the automated commit. CI runners (e.g. actions/checkout) do not
# configure a git user, so a bare `git commit` fails with exit 128
# ("Author identity unknown"). Pass the identity inline so the fix-agent commit
# succeeds regardless of the runner's ambient git config.
BOT_NAME = "memory-bank release-verify"
BOT_EMAIL = "release-verify@users.noreply.github.com"


def create_branch(branch_name: str) -> None:
    subprocess.run(
        ["git", "-C", str(REPO_ROOT), "checkout", "-b", branch_name],
        check=True,
        capture_output=True,
    )


def commit_fix(patch_files: list[str], test_file: str, check_name: str) -> None:
    all_files = patch_files + [test_file]
    subprocess.run(
        ["git", "-C", str(REPO_ROOT), "add", *all_files],
        check=True,
        capture_output=True,
    )
    subprocess.run(
        [
            "git",
            "-C",
            str(REPO_ROOT),
            "-c",
            f"user.name={BOT_NAME}",
            "-c",
            f"user.email={BOT_EMAIL}",
            "commit",
            "-m",
            f"fix: {check_name} regression detected by release-verify\n\nAuto-generated by release verification agent.",
        ],
        check=True,
        capture_output=True,
    )


def open_pr(
    branch: str,
    check_name: str,
    explanation: str,
    failing_checks: list[Any],
) -> str:
    table_rows = "\n".join(
        f"| {c.name} | {c.status} | {c.actual} |" for c in failing_checks
    )
    body = (
        f"## Regression detected by release-verify\n\n"
        f"| Check | Status | Actual |\n|---|---|---|\n{table_rows}\n\n"
        f"## Fix explanation\n\n{explanation}\n\n"
        f"_Auto-generated. Tests pass before this PR was opened._"
    )
    result = subprocess.run(
        [
            "gh",
            "pr",
            "create",
            "--title",
            f"fix: {check_name} regression",
            "--body",
            body,
            "--label",
            "automated",
            "--label",
            "regression",
            "--head",
            branch,
        ],
        capture_output=True,
        text=True,
        check=True,
        cwd=str(REPO_ROOT),
    )
    return result.stdout.strip()


def _ensure_label(name: str, color: str = "ededed", description: str = "") -> None:
    """Idempotently create a GitHub label so 'gh issue create --label' won't fail."""
    subprocess.run(
        ["gh", "label", "create", name, "--color", color, "--description", description, "--force"],
        capture_output=True,
        text=True,
        cwd=str(REPO_ROOT),
        check=False,
    )


def open_issue(check_name: str, iteration_log: str) -> str:
    body = (
        f"## Release verify agent exhausted retries\n\n"
        f"**Failing check:** `{check_name}`\n\n"
        f"## Iteration log\n\n```\n{iteration_log}\n```\n\n"
        f"_Auto-generated. Manual fix required._"
    )
    _ensure_label("automated", description="Created by automation")
    result = subprocess.run(
        [
            "gh",
            "issue",
            "create",
            "--title",
            f"[release-verify] agent failed: {check_name}",
            "--body",
            body,
            "--label",
            "automated",
        ],
        capture_output=True,
        text=True,
        check=True,
        cwd=str(REPO_ROOT),
    )
    return result.stdout.strip()


def push_branch(branch: str) -> None:
    subprocess.run(
        ["git", "-C", str(REPO_ROOT), "push", "origin", branch],
        check=True,
        capture_output=True,
    )
